deployment:
  tasks:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --optimize-autoloader
    - cp .env.production .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
